openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Calories
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
paths:
  /baseProducts:
    get:
      summary: Page of base products
      operationId: pageProducts
      tags:
        - baseProduct
      parameters:
        - name: name
          in: query
          description: filter by name of baseProduct
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: a page of base products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOfBaseProductDto"
    post:
      summary: create new base product
      operationId: createBaseProduct
      tags:
        - baseProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBaseProductRequest"
      responses:
        '201':
          description: created base product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseProductDto"
  /baseProducts/{baseProductId}:
    get:
      summary: get base product by id
      operationId: baseProductById
      tags:
        - baseProduct
      parameters:
        - name: baseProductId
          in: path
          required: true
          description: The id of the base product to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: base product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseProductDto"
    put:
      summary: update new base product
      operationId: updateBaseProduct
      tags:
        - baseProduct
      parameters:
        - name: baseProductId
          in: path
          required: true
          description: The id of the base product to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBaseProductRequest"
      responses:
        '200':
          description: updated base product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseProductDto"
    delete:
      summary: delete base prodcut
      operationId: deleteBaseProduct
      tags:
        - baseProduct
      parameters:
        - name: baseProductId
          in: path
          required: true
          description: The id of the base product to delete
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: base product deleted successfully
  /api/v1/dish:
    get:
      summary: Page of dishes
      operationId: pageDishes
      tags:
        - dish
      parameters:
        - name: name
          in: query
          description: filter by name of dish
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: a page of dishes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOfDishDto"
    post:
      summary: create dish
      operationId: createDish
      tags:
        - dish
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDishDto"
      responses:
        '201':
          description: created dish
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DishDto"
  /api/v1/dish/{dishId}:
    get:
      summary: get dish by id
      operationId: findDishById
      tags:
        - dish
      parameters:
        - name: dishId
          in: path
          required: true
          description: The id of the dish to update
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: dish
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DishDto"
    put:
      summary: update dish
      operationId: updateDish
      tags:
        - dish
      parameters:
        - name: dishId
          in: path
          required: true
          description: The id of the dish to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDishDto"
      responses:
        '200':
          description: updated dish
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DishDto"
    delete:
      summary: delete dish
      operationId: deleteDish
      tags:
        - dish
      parameters:
        - name: dishId
          in: path
          required: true
          description: The id of the dish to delete
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: dish deleted successfully
  /api/v1/dish/{dishId}/portion:
    post:
      summary: add portion to dish
      operationId: createPortion
      tags:
        - dish
      parameters:
        - name: dishId
          in: path
          required: true
          description: The id of the dish to which portion belong
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePortionDto"
      responses:
        '201':
          description: created portion
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PortionDto"
  /api/v1/dish/{dishId}/portion/{portionId}:
    put:
      summary: updated portion
      operationId: updatePortion
      tags:
        - dish
      parameters:
        - name: dishId
          in: path
          required: true
          description: The id of the dish to which portion belong
          schema:
            type: integer
            format: int64
        - name: portionId
          in: path
          required: true
          description: The id of the portion to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePortionDto"
      responses:
        '200':
          description: updated dish
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PortionDto"
    delete:
      summary: delete portion
      operationId: deletePortion
      tags:
        - dish
      parameters:
        - name: dishId
          in: path
          required: true
          description: The id of the dish to which portion belong
          schema:
            type: integer
            format: int64
        - name: portionId
          in: path
          required: true
          description: The id of the portion to delete
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: portion deleted successfully
  /api/v1/mealHistory:
    get:
      summary: get meal history
      operationId: getMealHistory
      tags:
        - mealHistory
      parameters:
        - name: date
          in: query
          description: filter by meal consumed at date
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: meal history
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MealHistoryListDto"
    post:
      summary: create new meal history
      operationId: createMealHistory
      tags:
        - mealHistory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMealHistoryDto"
      responses:
        '201':
          description: created meal history
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MealHistoryDto"
  /api/v1/mealHistory/{mealHistoryId}:
    put:
      summary: update meal history
      operationId: updateMealHistory
      tags:
        - mealHistory
      parameters:
        - name: mealHistoryId
          in: path
          required: true
          description: The id of the meal history
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateMealHistoryDto"
      responses:
        '200':
          description: updated meal history
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MealHistoryDto"
    delete:
      summary: delete meal history
      operationId: deleteMealHistory
      tags:
        - mealHistory
      parameters:
        - name: mealHistoryId
          in: path
          required: true
          description: The id of the meal history
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: meal history deleted successfully
  /api/v1/suggest:
    get:
      summary: get entity by string representation
      operationId: suggestEntity
      tags:
        - suggest
      parameters:
        - name: name
          in: query
          description: filter entity of type by string representation
          required: true
          schema:
            type: string
        - name: type
          in: query
          description: type of entity for search
          required: true
          schema:
            $ref: "#/components/schemas/EntityTypeDto"
      responses:
        '200':
          description: suggest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuggestDto"

components:
  schemas:
    CreateBaseProductRequest:
      type: object
      required:
        - name
        - nutrients
      properties:
        name:
          type: string
        nutrients:
          $ref: "#/components/schemas/NutrientsDto"
    UpdateBaseProductRequest:
      type: object
      required:
        - name
        - nutrients
      properties:
        name:
          type: string
        nutrients:
          $ref: "#/components/schemas/NutrientsDto"
    NutrientsDto:
      type: object
      required:
        - kcal
        - proteins
        - fats
        - carbs
      properties:
        kcal:
          type: number
          format: double
        proteins:
          type: number
          format: double
        fats:
          type: number
          format: double
        carbs:
          type: number
          format: double
    BaseProductDto:
      type: object
      required:
        - id
        - name
        - nutrients
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        nutrients:
          $ref: "#/components/schemas/NutrientsDto"
    PageOfBaseProductDto:
      type: object
      required:
        - content
      properties:
        size:
          type: integer
        number:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        content:
          type: array
          items:
            $ref: "#/components/schemas/BaseProductDto"
    PortionDto:
      type: object
      required:
        - id
        - grams
        - baseProduct
      properties:
        id:
          type: integer
          format: int64
        grams:
          type: integer
        baseProduct:
          $ref: "#/components/schemas/BaseProductDto"
    DishDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        portions:
          type: array
          items:
            $ref: "#/components/schemas/PortionDto"
    PageOfDishDto:
      type: object
      required:
        - content
      properties:
        size:
          type: integer
        number:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        content:
          type: array
          items:
            $ref: "#/components/schemas/DishDto"
    CreatePortionDto:
      type: object
      required:
        - grams
        - baseProductId
      properties:
        grams:
          type: integer
        baseProductId:
          type: integer
          format: int64
    UpdatePortionDto:
      type: object
      required:
        - grams
        - baseProductId
      properties:
        grams:
          type: integer
        baseProductId:
          type: integer
          format: int64
    CreateDishDto:
      type: object
      required:
        - name
        - portions
      properties:
        name:
          type: string
        portions:
          type: array
          items:
            $ref: "#/components/schemas/CreatePortionDto"
    UpdateDishDto:
      required:
        - name
      properties:
        name:
          type: string
    CreateMealHistoryDto:
      required:
        - dishId
      properties:
        dishId:
          type: integer
          format: int64
    UpdateMealHistoryDto:
      required:
        - id
        - dishId
      properties:
        dishId:
          type: integer
          format: int64
        consumedAt:
          type: string
          format: date-time
    MealHistoryListDto:
      required:
        - content
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/MealHistoryDto"
    MealHistoryDto:
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        consumedAt:
          type: string
          format: date-time
        nutrients:
          $ref: "#/components/schemas/NutrientsDto"
    SuggestDto:
      type: object
      required:
        - content
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/EntityDto"
    EntityDto:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          $ref: "#/components/schemas/EntityTypeDto"
    EntityTypeDto:
      type: string
      enum:
        - BASE_PRODUCT
        - DISH
